"""Deterministic risk triage for agent-facing OIA process records.

These scans flag issues for review. They do not classify information legally and
must not be used as autonomous withholding/redaction decisions.
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field

from foi_o_nz.constants import RISK_ASSESSMENT_SCHEMA_VERSION
from foi_o_nz.io import iter_jsonl, write_jsonl

EMAIL_RE = re.compile(r"\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b", re.IGNORECASE)
PHONE_RE = re.compile(r"(?<!\d)(?:\+?64|0)\s?\d{1,2}[\s-]?\d{3,4}[\s-]?\d{3,4}(?!\d)")
DATE_OF_BIRTH_RE = re.compile(r"\b(?:date of birth|dob|born)\b", re.IGNORECASE)
NHI_RE = re.compile(r"\b[A-Z]{3}\d{4}\b", re.IGNORECASE)
WITHHOLDING_RE = re.compile(r"\b(withhold|withheld|refuse|refused|redact|redacted|section\s+\d+)\b", re.IGNORECASE)
CONSULTATION_RE = re.compile(r"\b(consult|third party|commercial|confidential|privacy)\b", re.IGNORECASE)
AI_RE = re.compile(r"\b(ai|llm|chatgpt|generated by|bot|automated request)\b", re.IGNORECASE)


class RiskHit(BaseModel):
    """One deterministic risk indicator hit."""

    model_config = ConfigDict(extra="forbid")

    category: str
    pattern_id: str
    count: int = Field(ge=1)
    rationale: str


class RiskAssessment(BaseModel):
    """Risk triage result for one source record."""

    model_config = ConfigDict(extra="forbid")

    schema_version: Literal["foi-o-nz.risk-assessment.v0.1.0"] = RISK_ASSESSMENT_SCHEMA_VERSION
    assessment_id: str
    source_record_type: Literal["request", "event", "chunk", "unknown"]
    source_id: str
    request_id: str | None = None
    risk_level: Literal["low", "medium", "high"]
    review_required: bool
    hits: list[RiskHit] = Field(default_factory=list)
    limitations: list[str] = Field(default_factory=list)


def _record_text(record: dict[str, Any]) -> str:
    parts: list[str] = []
    for key in ("title", "authority", "source_state", "normalised_state", "text", "event_type", "lifecycle_state_after"):
        value = record.get(key)
        if value is not None:
            parts.append(str(value))
    payload = record.get("payload")
    if isinstance(payload, dict):
        parts.extend(str(value) for value in payload.values() if not isinstance(value, dict | list))
    for message in record.get("messages", []) if isinstance(record.get("messages"), list) else []:
        if isinstance(message, dict):
            parts.append(str(message.get("body") or message.get("text") or ""))
    for evidence in record.get("evidence", []) if isinstance(record.get("evidence"), list) else []:
        if isinstance(evidence, dict):
            parts.append(str(evidence.get("excerpt") or ""))
    return "\n".join(part for part in parts if part)


def _source_id(record: dict[str, Any], sequence: int) -> str:
    if record.get("event_id"):
        return str(record["event_id"])
    if record.get("chunk_id"):
        return str(record["chunk_id"])
    if record.get("request_id"):
        return str(record["request_id"])
    request_ref = record.get("request_ref")
    if isinstance(request_ref, dict) and request_ref.get("source_request_id") is not None:
        return str(request_ref["source_request_id"])
    return f"record-{sequence}"


def _request_id(record: dict[str, Any]) -> str | None:
    if record.get("request_id") is not None:
        return str(record["request_id"])
    request_ref = record.get("request_ref")
    if isinstance(request_ref, dict) and request_ref.get("source_request_id") is not None:
        return str(request_ref["source_request_id"])
    return None


def infer_record_type(record: dict[str, Any]) -> Literal["request", "event", "chunk", "unknown"]:
    """Infer a supported risk source type."""
    if record.get("event_type") and record.get("event_id"):
        return "event"
    if record.get("chunk_id"):
        return "chunk"
    if record.get("request_id") and record.get("authority"):
        return "request"
    return "unknown"


def assess_record_risk(record: dict[str, Any], *, sequence: int = 0) -> RiskAssessment:
    """Assess one record with deterministic review-trigger patterns."""
    text = _record_text(record)
    hits: list[RiskHit] = []
    checks = [
        ("personal_information", "email", EMAIL_RE, "Email-like personal data appears in text."),
        ("personal_information", "phone", PHONE_RE, "Phone-like personal data appears in text."),
        ("personal_information", "date_of_birth", DATE_OF_BIRTH_RE, "Date-of-birth language appears in text."),
        ("health_information", "nhi", NHI_RE, "Possible NZ NHI-like identifier appears in text."),
        ("withholding_or_redaction", "withholding_language", WITHHOLDING_RE, "Withholding/refusal/redaction language appears in text."),
        ("consultation", "consultation_language", CONSULTATION_RE, "Consultation/privacy/commercial-confidence language appears in text."),
        ("ai_workload", "ai_language", AI_RE, "AI/bot/generated-request language appears in text."),
    ]
    for category, pattern_id, regex, rationale in checks:
        count = len(regex.findall(text))
        if count:
            hits.append(RiskHit(category=category, pattern_id=pattern_id, count=count, rationale=rationale))
    score = sum(hit.count for hit in hits) + sum(2 for hit in hits if hit.category in {"personal_information", "health_information"})
    risk_level: Literal["low", "medium", "high"] = "low"
    if score >= 5 or any(hit.category == "health_information" for hit in hits):
        risk_level = "high"
    elif score >= 2 or hits:
        risk_level = "medium"
    return RiskAssessment(
        assessment_id=f"foio-nz:risk:{_source_id(record, sequence)}",
        source_record_type=infer_record_type(record),
        source_id=_source_id(record, sequence),
        request_id=_request_id(record),
        risk_level=risk_level,
        review_required=bool(hits),
        hits=hits,
        limitations=[
            "Deterministic triage only; not a legal classification, redaction, or withholding decision.",
            "False positives and false negatives are expected; human review is required before action.",
        ],
    )


def risk_scan_jsonl(input_jsonl: Path, output_jsonl: Path) -> dict[str, Any]:
    """Scan a JSONL stream and write risk-assessment JSONL."""
    assessments = [
        assess_record_risk(record, sequence=sequence).model_dump(mode="json", exclude_none=True)
        for sequence, record in enumerate(iter_jsonl(input_jsonl))
    ]
    write_jsonl(output_jsonl, assessments)
    counts: dict[str, int] = {"low": 0, "medium": 0, "high": 0}
    for assessment in assessments:
        counts[str(assessment["risk_level"])] += 1
    return {
        "ok": True,
        "input": str(input_jsonl),
        "output": str(output_jsonl),
        "assessment_count": len(assessments),
        "risk_level_counts": counts,
        "review_required_count": sum(1 for assessment in assessments if assessment["review_required"]),
    }
