"""Sub-national and devolved statutory profiles for global jurisdictions.

Covers:
- UK Devolved Administrations (England, Scotland, Wales, Northern Ireland)
- US States & Territories (50 States, DC, PR, GU, VI)
- Canadian Provinces & Territories (10 Provinces, 3 Territories)
- German Bundesländer (16 States)
- Spanish Comunidades Autónomas (17 Autonomous Communities, 2 Autonomous Cities)
- Swiss Cantons & Latin American Federations
"""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict


class StrictModel(BaseModel):
    """Forbid undeclared fields in subnational contracts."""

    model_config = ConfigDict(extra="forbid")


class SubnationalStatutoryProfile(StrictModel):
    """Detailed statutory parameters for a sub-national or devolved regime."""

    jurisdiction: str
    regime: str
    statute_name: str
    statutory_timeframe_days: int
    timeframe_type: Literal["working_days", "calendar_days"]
    default_agency_scope: str
    exemption_clauses: list[str]
    parent_jurisdiction: str
    level: Literal[
        "national",
        "state_or_province",
        "territory",
        "devolved_nation",
        "autonomous_community",
        "canton",
        "supranational",
    ] = "state_or_province"


# 1. UK Devolved Nations & Environmental Regimes
UK_DEVOLVED_PROFILES: dict[str, SubnationalStatutoryProfile] = {
    "UK-ENG-FOIA": SubnationalStatutoryProfile(
        jurisdiction="UK-ENG-FOIA",
        regime="FOIA",
        statute_name="Freedom of Information Act 2000 (England & UK-Wide)",
        statutory_timeframe_days=20,
        timeframe_type="working_days",
        default_agency_scope="UK Government Departments & English Public Authorities",
        exemption_clauses=["s21", "s22", "s30", "s35", "s36", "s40", "s42", "s43"],
        parent_jurisdiction="UK",
        level="devolved_nation",
    ),
    "UK-WALES-FOIA": SubnationalStatutoryProfile(
        jurisdiction="UK-WALES-FOIA",
        regime="FOIA",
        statute_name="Freedom of Information Act 2000 (Wales) & Welsh Language Standards",
        statutory_timeframe_days=20,
        timeframe_type="working_days",
        default_agency_scope="Welsh Government, Senedd Cymru, Welsh Local Authorities & NHS Wales",
        exemption_clauses=["s21", "s22", "s35", "s36", "s40", "s42"],
        parent_jurisdiction="UK",
        level="devolved_nation",
    ),
    "UK-NI-FOIA": SubnationalStatutoryProfile(
        jurisdiction="UK-NI-FOIA",
        regime="FOIA",
        statute_name="Freedom of Information Act 2000 (Northern Ireland)",
        statutory_timeframe_days=20,
        timeframe_type="working_days",
        default_agency_scope="Northern Ireland Executive Departments, Assembly & District Councils",
        exemption_clauses=["s21", "s22", "s35", "s36", "s40", "s42"],
        parent_jurisdiction="UK",
        level="devolved_nation",
    ),
    "SCOT-FOISA": SubnationalStatutoryProfile(
        jurisdiction="SCOT-FOISA",
        regime="FOISA",
        statute_name="Freedom of Information (Scotland) Act 2002",
        statutory_timeframe_days=20,
        timeframe_type="working_days",
        default_agency_scope="Scottish Government, Scottish Parliament, Local Councils & NHS Scotland",
        exemption_clauses=["s25", "s27", "s30", "s33", "s36", "s38"],
        parent_jurisdiction="UK",
        level="devolved_nation",
    ),
    "SCOT-EIR": SubnationalStatutoryProfile(
        jurisdiction="SCOT-EIR",
        regime="EIR",
        statute_name="Environmental Information (Scotland) Regulations 2004",
        statutory_timeframe_days=20,
        timeframe_type="working_days",
        default_agency_scope="Scottish Public Authorities holding environmental information",
        exemption_clauses=["r10(4)", "r10(5)", "r11"],
        parent_jurisdiction="UK",
        level="devolved_nation",
    ),
}

# 2. US 50 States, DC, & Territories
US_SUBNATIONAL_PROFILES: dict[str, SubnationalStatutoryProfile] = {
    "US-AL": SubnationalStatutoryProfile(
        jurisdiction="US-AL",
        regime="Open Records",
        statute_name="Alabama Open Records Act (Ala. Code § 36-12-40)",
        statutory_timeframe_days=10,
        timeframe_type="working_days",
        default_agency_scope="Alabama State and Municipal Agencies",
        exemption_clauses=["§ 36-12-40 exceptions", "Executive Privilege"],
        parent_jurisdiction="US",
    ),
    "US-AK": SubnationalStatutoryProfile(
        jurisdiction="US-AK",
        regime="PRA",
        statute_name="Alaska Public Records Act (AS 40.25.110)",
        statutory_timeframe_days=10,
        timeframe_type="working_days",
        default_agency_scope="Alaska State Agencies & Boroughs",
        exemption_clauses=["AS 40.25.120"],
        parent_jurisdiction="US",
    ),
    "US-AZ": SubnationalStatutoryProfile(
        jurisdiction="US-AZ",
        regime="Public Records",
        statute_name="Arizona Public Records Law (A.R.S. § 39-121)",
        statutory_timeframe_days=15,
        timeframe_type="working_days",
        default_agency_scope="Arizona State, County, and City Bodies",
        exemption_clauses=["A.R.S. § 39-121.01(D)", "Confidentiality Statutes"],
        parent_jurisdiction="US",
    ),
    "US-AR": SubnationalStatutoryProfile(
        jurisdiction="US-AR",
        regime="FOIA",
        statute_name="Arkansas Freedom of Information Act (Ark. Code Ann. § 25-19-101)",
        statutory_timeframe_days=3,
        timeframe_type="working_days",
        default_agency_scope="Arkansas State and Local Entities",
        exemption_clauses=["§ 25-19-105(b)"],
        parent_jurisdiction="US",
    ),
    "US-CA": SubnationalStatutoryProfile(
        jurisdiction="US-CA",
        regime="CPRA",
        statute_name="California Public Records Act (Cal. Gov. Code § 7920.000)",
        statutory_timeframe_days=10,
        timeframe_type="calendar_days",
        default_agency_scope="California State and Local Public Agencies",
        exemption_clauses=["Gov Code § 7927.705", "§ 7927.700", "§ 7922.000"],
        parent_jurisdiction="US",
    ),
    "US-CO": SubnationalStatutoryProfile(
        jurisdiction="US-CO",
        regime="CORA",
        statute_name="Colorado Open Records Act (C.R.S. § 24-72-201)",
        statutory_timeframe_days=3,
        timeframe_type="working_days",
        default_agency_scope="Colorado State and Municipal Entities",
        exemption_clauses=["C.R.S. § 24-72-204"],
        parent_jurisdiction="US",
    ),
    "US-CT": SubnationalStatutoryProfile(
        jurisdiction="US-CT",
        regime="FOIA",
        statute_name="Connecticut Freedom of Information Act (Conn. Gen. Stat. § 1-200)",
        statutory_timeframe_days=4,
        timeframe_type="working_days",
        default_agency_scope="Connecticut Executive, Legislative and Local Bodies",
        exemption_clauses=["Conn. Gen. Stat. § 1-210(b)"],
        parent_jurisdiction="US",
    ),
    "US-DE": SubnationalStatutoryProfile(
        jurisdiction="US-DE",
        regime="FOIA",
        statute_name="Delaware Freedom of Information Act (29 Del. C. § 10001)",
        statutory_timeframe_days=15,
        timeframe_type="working_days",
        default_agency_scope="Delaware Public Bodies",
        exemption_clauses=["29 Del. C. § 10002(o)"],
        parent_jurisdiction="US",
    ),
    "US-FL": SubnationalStatutoryProfile(
        jurisdiction="US-FL",
        regime="Sunshine Law",
        statute_name="Florida Public Records Act (Fla. Stat. ch. 119 / Sunshine Law)",
        statutory_timeframe_days=7,
        timeframe_type="working_days",
        default_agency_scope="Florida State, County, and Municipal Agencies",
        exemption_clauses=["Fla. Stat. § 119.071"],
        parent_jurisdiction="US",
    ),
    "US-GA": SubnationalStatutoryProfile(
        jurisdiction="US-GA",
        regime="Open Records",
        statute_name="Georgia Open Records Act (O.C.G.A. § 50-18-70)",
        statutory_timeframe_days=3,
        timeframe_type="working_days",
        default_agency_scope="Georgia State and Local Authorities",
        exemption_clauses=["O.C.G.A. § 50-18-72"],
        parent_jurisdiction="US",
    ),
    "US-HI": SubnationalStatutoryProfile(
        jurisdiction="US-HI",
        regime="UIPA",
        statute_name="Hawaii Uniform Information Practices Act (HRS Chapter 92F)",
        statutory_timeframe_days=10,
        timeframe_type="working_days",
        default_agency_scope="Hawaii State and County Government Agencies",
        exemption_clauses=["HRS § 92F-13"],
        parent_jurisdiction="US",
    ),
    "US-ID": SubnationalStatutoryProfile(
        jurisdiction="US-ID",
        regime="PRA",
        statute_name="Idaho Public Records Act (Idaho Code § 74-101)",
        statutory_timeframe_days=3,
        timeframe_type="working_days",
        default_agency_scope="Idaho State and Local Public Agencies",
        exemption_clauses=["Idaho Code §§ 74-104 to 74-111"],
        parent_jurisdiction="US",
    ),
    "US-IL": SubnationalStatutoryProfile(
        jurisdiction="US-IL",
        regime="FOIA",
        statute_name="Illinois Freedom of Information Act (5 ILCS 140)",
        statutory_timeframe_days=5,
        timeframe_type="working_days",
        default_agency_scope="Illinois State and Municipal Public Bodies",
        exemption_clauses=["5 ILCS 140/7", "5 ILCS 140/7.5"],
        parent_jurisdiction="US",
    ),
    "US-IN": SubnationalStatutoryProfile(
        jurisdiction="US-IN",
        regime="APRA",
        statute_name="Indiana Access to Public Records Act (IC 5-14-3)",
        statutory_timeframe_days=7,
        timeframe_type="working_days",
        default_agency_scope="Indiana Public Agencies",
        exemption_clauses=["IC 5-14-3-4"],
        parent_jurisdiction="US",
    ),
    "US-IA": SubnationalStatutoryProfile(
        jurisdiction="US-IA",
        regime="Open Records",
        statute_name="Iowa Open Records Act (Iowa Code Chapter 22)",
        statutory_timeframe_days=10,
        timeframe_type="working_days",
        default_agency_scope="Iowa Government Bodies",
        exemption_clauses=["Iowa Code § 22.7"],
        parent_jurisdiction="US",
    ),
    "US-KS": SubnationalStatutoryProfile(
        jurisdiction="US-KS",
        regime="KORA",
        statute_name="Kansas Open Records Act (K.S.A. 45-215)",
        statutory_timeframe_days=3,
        timeframe_type="working_days",
        default_agency_scope="Kansas Public Agencies",
        exemption_clauses=["K.S.A. 45-221"],
        parent_jurisdiction="US",
    ),
    "US-KY": SubnationalStatutoryProfile(
        jurisdiction="US-KY",
        regime="Open Records",
        statute_name="Kentucky Open Records Act (KRS 61.870)",
        statutory_timeframe_days=5,
        timeframe_type="working_days",
        default_agency_scope="Kentucky Public Agencies",
        exemption_clauses=["KRS 61.878"],
        parent_jurisdiction="US",
    ),
    "US-LA": SubnationalStatutoryProfile(
        jurisdiction="US-LA",
        regime="Public Records",
        statute_name="Louisiana Public Records Law (La. R.S. 44:1)",
        statutory_timeframe_days=3,
        timeframe_type="working_days",
        default_agency_scope="Louisiana State and Municipal Custodians",
        exemption_clauses=["La. R.S. 44:4.1"],
        parent_jurisdiction="US",
    ),
    "US-ME": SubnationalStatutoryProfile(
        jurisdiction="US-ME",
        regime="FOAA",
        statute_name="Maine Freedom of Access Act (1 M.R.S. § 401)",
        statutory_timeframe_days=5,
        timeframe_type="working_days",
        default_agency_scope="Maine Public Bodies & Agencies",
        exemption_clauses=["1 M.R.S. § 402(3)"],
        parent_jurisdiction="US",
    ),
    "US-MD": SubnationalStatutoryProfile(
        jurisdiction="US-MD",
        regime="PIA",
        statute_name="Maryland Public Information Act (Md. Code, Gen. Prov. § 4-101)",
        statutory_timeframe_days=30,
        timeframe_type="calendar_days",
        default_agency_scope="Maryland State and Local Government Units",
        exemption_clauses=["GP §§ 4-301 to 4-356"],
        parent_jurisdiction="US",
    ),
    "US-MA": SubnationalStatutoryProfile(
        jurisdiction="US-MA",
        regime="Public Records",
        statute_name="Massachusetts Public Records Law (M.G.L. c. 66, § 10)",
        statutory_timeframe_days=10,
        timeframe_type="working_days",
        default_agency_scope="Massachusetts State and Municipal Agencies",
        exemption_clauses=["M.G.L. c. 4, § 7(26)"],
        parent_jurisdiction="US",
    ),
    "US-MI": SubnationalStatutoryProfile(
        jurisdiction="US-MI",
        regime="FOIA",
        statute_name="Michigan Freedom of Information Act (MCL 15.231)",
        statutory_timeframe_days=5,
        timeframe_type="working_days",
        default_agency_scope="Michigan Public Bodies",
        exemption_clauses=["MCL 15.243"],
        parent_jurisdiction="US",
    ),
    "US-MN": SubnationalStatutoryProfile(
        jurisdiction="US-MN",
        regime="MGDPA",
        statute_name="Minnesota Government Data Practices Act (Minn. Stat. § 13.01)",
        statutory_timeframe_days=10,
        timeframe_type="working_days",
        default_agency_scope="Minnesota State Agencies and Political Subdivisions",
        exemption_clauses=["Minn. Stat. § 13.02", "Specific Classifications"],
        parent_jurisdiction="US",
    ),
    "US-MS": SubnationalStatutoryProfile(
        jurisdiction="US-MS",
        regime="Public Records",
        statute_name="Mississippi Public Records Act (Miss. Code Ann. § 25-61-1)",
        statutory_timeframe_days=7,
        timeframe_type="working_days",
        default_agency_scope="Mississippi Public Bodies",
        exemption_clauses=["Miss. Code Ann. § 25-61-9"],
        parent_jurisdiction="US",
    ),
    "US-MO": SubnationalStatutoryProfile(
        jurisdiction="US-MO",
        regime="Sunshine Law",
        statute_name="Missouri Sunshine Law (RSMo Chapter 610)",
        statutory_timeframe_days=3,
        timeframe_type="working_days",
        default_agency_scope="Missouri Public Governmental Bodies",
        exemption_clauses=["RSMo § 610.021"],
        parent_jurisdiction="US",
    ),
    "US-MT": SubnationalStatutoryProfile(
        jurisdiction="US-MT",
        regime="Right to Know",
        statute_name="Montana Public Records Act (MCA 2-6-1001)",
        statutory_timeframe_days=5,
        timeframe_type="working_days",
        default_agency_scope="Montana State and Local Public Agencies",
        exemption_clauses=["MCA 2-6-1002", "Constitutional Privacy Test"],
        parent_jurisdiction="US",
    ),
    "US-NE": SubnationalStatutoryProfile(
        jurisdiction="US-NE",
        regime="Public Records",
        statute_name="Nebraska Public Records Statutes (Neb. Rev. Stat. § 84-712)",
        statutory_timeframe_days=4,
        timeframe_type="working_days",
        default_agency_scope="Nebraska Public Bodies",
        exemption_clauses=["Neb. Rev. Stat. § 84-712.05"],
        parent_jurisdiction="US",
    ),
    "US-NV": SubnationalStatutoryProfile(
        jurisdiction="US-NV",
        regime="NPRA",
        statute_name="Nevada Public Records Act (NRS Chapter 239)",
        statutory_timeframe_days=5,
        timeframe_type="working_days",
        default_agency_scope="Nevada State and Local Government Entities",
        exemption_clauses=["NRS 239.010 Table of Exceptions"],
        parent_jurisdiction="US",
    ),
    "US-NH": SubnationalStatutoryProfile(
        jurisdiction="US-NH",
        regime="Right-to-Know",
        statute_name="New Hampshire Right-to-Know Law (RSA 91-A)",
        statutory_timeframe_days=5,
        timeframe_type="working_days",
        default_agency_scope="New Hampshire Public Bodies & Agencies",
        exemption_clauses=["RSA 91-A:5"],
        parent_jurisdiction="US",
    ),
    "US-NJ": SubnationalStatutoryProfile(
        jurisdiction="US-NJ",
        regime="OPRA",
        statute_name="New Jersey Open Public Records Act (N.J.S.A. 47:1A-1)",
        statutory_timeframe_days=7,
        timeframe_type="working_days",
        default_agency_scope="New Jersey State, County, and Municipal Entities",
        exemption_clauses=["N.J.S.A. 47:1A-1.1", "Executive Orders"],
        parent_jurisdiction="US",
    ),
    "US-NM": SubnationalStatutoryProfile(
        jurisdiction="US-NM",
        regime="IPRA",
        statute_name="New Mexico Inspection of Public Records Act (NMSA 1978, § 14-2-1)",
        statutory_timeframe_days=15,
        timeframe_type="calendar_days",
        default_agency_scope="New Mexico Public Bodies",
        exemption_clauses=["NMSA 1978, § 14-2-1(A)"],
        parent_jurisdiction="US",
    ),
    "US-NY": SubnationalStatutoryProfile(
        jurisdiction="US-NY",
        regime="FOIL",
        statute_name="New York Freedom of Information Law (Public Officers Law § 84)",
        statutory_timeframe_days=5,
        timeframe_type="working_days",
        default_agency_scope="New York State and Municipal Agencies",
        exemption_clauses=["POL § 87(2)"],
        parent_jurisdiction="US",
    ),
    "US-NC": SubnationalStatutoryProfile(
        jurisdiction="US-NC",
        regime="Public Records",
        statute_name="North Carolina Public Records Law (N.C.G.S. Chapter 132)",
        statutory_timeframe_days=10,
        timeframe_type="working_days",
        default_agency_scope="North Carolina Public Agencies",
        exemption_clauses=["N.C.G.S. § 132-1.1 to 132-1.14"],
        parent_jurisdiction="US",
    ),
    "US-ND": SubnationalStatutoryProfile(
        jurisdiction="US-ND",
        regime="Open Records",
        statute_name="North Dakota Open Records Law (N.D.C.C. § 44-04-18)",
        statutory_timeframe_days=5,
        timeframe_type="working_days",
        default_agency_scope="North Dakota Public Entities",
        exemption_clauses=["N.D.C.C. §§ 44-04-18.1 to 44-04-18.28"],
        parent_jurisdiction="US",
    ),
    "US-OH": SubnationalStatutoryProfile(
        jurisdiction="US-OH",
        regime="Public Records",
        statute_name="Ohio Public Records Act (Ohio Rev. Code § 149.43)",
        statutory_timeframe_days=10,
        timeframe_type="working_days",
        default_agency_scope="Ohio Public Offices",
        exemption_clauses=["R.C. 149.43(A)(1)"],
        parent_jurisdiction="US",
    ),
    "US-OK": SubnationalStatutoryProfile(
        jurisdiction="US-OK",
        regime="Open Records",
        statute_name="Oklahoma Open Records Act (51 O.S. § 24A.1)",
        statutory_timeframe_days=10,
        timeframe_type="working_days",
        default_agency_scope="Oklahoma Public Bodies",
        exemption_clauses=["51 O.S. §§ 24A.5 to 24A.29"],
        parent_jurisdiction="US",
    ),
    "US-OR": SubnationalStatutoryProfile(
        jurisdiction="US-OR",
        regime="Public Records",
        statute_name="Oregon Public Records Law (ORS 192.311)",
        statutory_timeframe_days=15,
        timeframe_type="working_days",
        default_agency_scope="Oregon Public Bodies",
        exemption_clauses=["ORS 192.345", "ORS 192.355"],
        parent_jurisdiction="US",
    ),
    "US-PA": SubnationalStatutoryProfile(
        jurisdiction="US-PA",
        regime="RTKL",
        statute_name="Pennsylvania Right-to-Know Law (65 P.S. § 67.101)",
        statutory_timeframe_days=5,
        timeframe_type="working_days",
        default_agency_scope="Pennsylvania Commonwealth, Local, and Legislative Agencies",
        exemption_clauses=["65 P.S. § 67.708(b)"],
        parent_jurisdiction="US",
    ),
    "US-RI": SubnationalStatutoryProfile(
        jurisdiction="US-RI",
        regime="APRA",
        statute_name="Rhode Island Access to Public Records Act (R.I. Gen. Laws § 38-2-1)",
        statutory_timeframe_days=10,
        timeframe_type="working_days",
        default_agency_scope="Rhode Island Public Bodies",
        exemption_clauses=["R.I. Gen. Laws § 38-2-2(4)"],
        parent_jurisdiction="US",
    ),
    "US-SC": SubnationalStatutoryProfile(
        jurisdiction="US-SC",
        regime="FOIA",
        statute_name="South Carolina Freedom of Information Act (S.C. Code Ann. § 30-4-10)",
        statutory_timeframe_days=15,
        timeframe_type="working_days",
        default_agency_scope="South Carolina Public Bodies",
        exemption_clauses=["S.C. Code Ann. § 30-4-40"],
        parent_jurisdiction="US",
    ),
    "US-SD": SubnationalStatutoryProfile(
        jurisdiction="US-SD",
        regime="Open Records",
        statute_name="South Dakota Public Records Law (SDCL 1-27)",
        statutory_timeframe_days=10,
        timeframe_type="working_days",
        default_agency_scope="South Dakota Public Agencies",
        exemption_clauses=["SDCL 1-27-1.5"],
        parent_jurisdiction="US",
    ),
    "US-TN": SubnationalStatutoryProfile(
        jurisdiction="US-TN",
        regime="TPRA",
        statute_name="Tennessee Public Records Act (Tenn. Code Ann. § 10-7-503)",
        statutory_timeframe_days=7,
        timeframe_type="working_days",
        default_agency_scope="Tennessee Governmental Entities",
        exemption_clauses=["Tenn. Code Ann. § 10-7-504"],
        parent_jurisdiction="US",
    ),
    "US-TX": SubnationalStatutoryProfile(
        jurisdiction="US-TX",
        regime="PIA",
        statute_name="Texas Public Information Act (Tex. Gov't Code Chapter 552)",
        statutory_timeframe_days=10,
        timeframe_type="working_days",
        default_agency_scope="Texas Governmental Bodies",
        exemption_clauses=["Tex. Gov't Code §§ 552.101 to 552.160"],
        parent_jurisdiction="US",
    ),
    "US-UT": SubnationalStatutoryProfile(
        jurisdiction="US-UT",
        regime="GRAMA",
        statute_name="Utah Government Records Access and Management Act (Utah Code § 63G-2-101)",
        statutory_timeframe_days=10,
        timeframe_type="working_days",
        default_agency_scope="Utah Governmental Entities",
        exemption_clauses=["Utah Code §§ 63G-2-302 to 63G-2-305"],
        parent_jurisdiction="US",
    ),
    "US-VT": SubnationalStatutoryProfile(
        jurisdiction="US-VT",
        regime="Public Records",
        statute_name="Vermont Public Records Act (1 V.S.A. § 315)",
        statutory_timeframe_days=3,
        timeframe_type="working_days",
        default_agency_scope="Vermont Public Agencies",
        exemption_clauses=["1 V.S.A. § 317(c)"],
        parent_jurisdiction="US",
    ),
    "US-VA": SubnationalStatutoryProfile(
        jurisdiction="US-VA",
        regime="VFOIA",
        statute_name="Virginia Freedom of Information Act (Va. Code § 2.2-3700)",
        statutory_timeframe_days=5,
        timeframe_type="working_days",
        default_agency_scope="Virginia Public Bodies",
        exemption_clauses=["Va. Code §§ 2.2-3705.1 to 2.2-3705.8"],
        parent_jurisdiction="US",
    ),
    "US-WA": SubnationalStatutoryProfile(
        jurisdiction="US-WA",
        regime="PRA",
        statute_name="Washington Public Records Act (RCW 42.56)",
        statutory_timeframe_days=5,
        timeframe_type="working_days",
        default_agency_scope="Washington State and Local Agencies",
        exemption_clauses=["RCW 42.56.210 to 42.56.480"],
        parent_jurisdiction="US",
    ),
    "US-WV": SubnationalStatutoryProfile(
        jurisdiction="US-WV",
        regime="FOIA",
        statute_name="West Virginia Freedom of Information Act (W. Va. Code § 29B-1-1)",
        statutory_timeframe_days=5,
        timeframe_type="working_days",
        default_agency_scope="West Virginia Public Bodies",
        exemption_clauses=["W. Va. Code § 29B-1-4"],
        parent_jurisdiction="US",
    ),
    "US-WI": SubnationalStatutoryProfile(
        jurisdiction="US-WI",
        regime="Public Records",
        statute_name="Wisconsin Public Records Law (Wis. Stat. §§ 19.31-19.39)",
        statutory_timeframe_days=10,
        timeframe_type="working_days",
        default_agency_scope="Wisconsin Authorities",
        exemption_clauses=["Wis. Stat. § 19.36", "Common Law Balancing Test"],
        parent_jurisdiction="US",
    ),
    "US-WY": SubnationalStatutoryProfile(
        jurisdiction="US-WY",
        regime="Public Records",
        statute_name="Wyoming Public Records Act (Wyo. Stat. Ann. § 16-4-201)",
        statutory_timeframe_days=30,
        timeframe_type="calendar_days",
        default_agency_scope="Wyoming Governmental Entities",
        exemption_clauses=["Wyo. Stat. Ann. § 16-4-203"],
        parent_jurisdiction="US",
    ),
    "US-DC": SubnationalStatutoryProfile(
        jurisdiction="US-DC",
        regime="FOIA",
        statute_name="District of Columbia Freedom of Information Act (D.C. Code § 2-531)",
        statutory_timeframe_days=15,
        timeframe_type="working_days",
        default_agency_scope="District of Columbia Executive Agencies & Council",
        exemption_clauses=["D.C. Code § 2-534"],
        parent_jurisdiction="US",
        level="territory",
    ),
    "US-PR": SubnationalStatutoryProfile(
        jurisdiction="US-PR",
        regime="Ley de Transparencia",
        statute_name="Ley de Transparencia y Acceso a la Información (Ley Núm. 141-2019 Puerto Rico)",
        statutory_timeframe_days=10,
        timeframe_type="working_days",
        default_agency_scope="Puerto Rico Public Entities",
        exemption_clauses=["Artículo 5"],
        parent_jurisdiction="US",
        level="territory",
    ),
}

# 3. Canadian 10 Provinces & 3 Territories
CANADIAN_SUBNATIONAL_PROFILES: dict[str, SubnationalStatutoryProfile] = {
    "CA-ON": SubnationalStatutoryProfile(
        jurisdiction="CA-ON",
        regime="FIPPA/MFIPPA",
        statute_name="Freedom of Information and Protection of Privacy Act (R.S.O. 1990, c. F.31 Ontario)",
        statutory_timeframe_days=30,
        timeframe_type="calendar_days",
        default_agency_scope="Ontario Ministries, Agencies, Hospitals, Universities & Municipalities",
        exemption_clauses=["s12", "s13", "s14", "s17", "s18", "s21"],
        parent_jurisdiction="CA",
    ),
    "CA-QC": SubnationalStatutoryProfile(
        jurisdiction="CA-QC",
        regime="Loi sur l'accès",
        statute_name="Loi sur l'accès aux documents des organismes publics (RLRQ c. A-2.1 Québec)",
        statutory_timeframe_days=20,
        timeframe_type="calendar_days",
        default_agency_scope="Québec Government Bodies, Municipalities & Health Agencies",
        exemption_clauses=["Art 18", "Art 21", "Art 28", "Art 53"],
        parent_jurisdiction="CA",
    ),
    "CA-BC": SubnationalStatutoryProfile(
        jurisdiction="CA-BC",
        regime="FIPPA",
        statute_name="Freedom of Information and Protection of Privacy Act (RSBC 1996 c. 165 BC)",
        statutory_timeframe_days=30,
        timeframe_type="working_days",
        default_agency_scope="British Columbia Public Bodies",
        exemption_clauses=["s12", "s13", "s14", "s15", "s17", "s22"],
        parent_jurisdiction="CA",
    ),
    "CA-AB": SubnationalStatutoryProfile(
        jurisdiction="CA-AB",
        regime="FOIP",
        statute_name="Freedom of Information and Protection of Privacy Act (RSA 2000 c. F-25 Alberta)",
        statutory_timeframe_days=30,
        timeframe_type="calendar_days",
        default_agency_scope="Alberta Public Bodies",
        exemption_clauses=["s16", "s17", "s20", "s24"],
        parent_jurisdiction="CA",
    ),
    "CA-MB": SubnationalStatutoryProfile(
        jurisdiction="CA-MB",
        regime="FIPPA",
        statute_name="Freedom of Information and Protection of Privacy Act (C.C.S.M. c. F175 Manitoba)",
        statutory_timeframe_days=30,
        timeframe_type="calendar_days",
        default_agency_scope="Manitoba Public Bodies",
        exemption_clauses=["s17", "s18", "s19", "s23"],
        parent_jurisdiction="CA",
    ),
    "CA-SK": SubnationalStatutoryProfile(
        jurisdiction="CA-SK",
        regime="FOIP/LAFOIP",
        statute_name="Freedom of Information and Protection of Privacy Act (SS 1990-91 c. F-22.01 Saskatchewan)",
        statutory_timeframe_days=30,
        timeframe_type="calendar_days",
        default_agency_scope="Saskatchewan Government Institutions and Local Authorities",
        exemption_clauses=["s16", "s17", "s19", "s29"],
        parent_jurisdiction="CA",
    ),
    "CA-NS": SubnationalStatutoryProfile(
        jurisdiction="CA-NS",
        regime="FOIPOP",
        statute_name="Freedom of Information and Protection of Privacy Act (SNS 1993 c. 5 Nova Scotia)",
        statutory_timeframe_days=30,
        timeframe_type="calendar_days",
        default_agency_scope="Nova Scotia Public Bodies",
        exemption_clauses=["s13", "s14", "s15", "s20"],
        parent_jurisdiction="CA",
    ),
    "CA-NB": SubnationalStatutoryProfile(
        jurisdiction="CA-NB",
        regime="RTIPPA",
        statute_name="Right to Information and Protection of Privacy Act (SNB 2009 c. R-10.6 New Brunswick)",
        statutory_timeframe_days=30,
        timeframe_type="calendar_days",
        default_agency_scope="New Brunswick Public Bodies",
        exemption_clauses=["s17", "s18", "s21", "s26"],
        parent_jurisdiction="CA",
    ),
    "CA-NL": SubnationalStatutoryProfile(
        jurisdiction="CA-NL",
        regime="ATIPPA",
        statute_name="Access to Information and Protection of Privacy Act, 2015 (SNL2015 c. A-1.2 NL)",
        statutory_timeframe_days=20,
        timeframe_type="working_days",
        default_agency_scope="Newfoundland and Labrador Public Bodies",
        exemption_clauses=["s27", "s29", "s31", "s39"],
        parent_jurisdiction="CA",
    ),
    "CA-PE": SubnationalStatutoryProfile(
        jurisdiction="CA-PE",
        regime="FOIPP",
        statute_name="Freedom of Information and Protection of Privacy Act (RSPEI 1988 c. F-15.01 PEI)",
        statutory_timeframe_days=30,
        timeframe_type="calendar_days",
        default_agency_scope="Prince Edward Island Public Bodies",
        exemption_clauses=["s14", "s15", "s18", "s22"],
        parent_jurisdiction="CA",
    ),
    "CA-YT": SubnationalStatutoryProfile(
        jurisdiction="CA-YT",
        regime="ATIPP",
        statute_name="Access to Information and Protection of Privacy Act (SY 2019 c. 12 Yukon)",
        statutory_timeframe_days=30,
        timeframe_type="calendar_days",
        default_agency_scope="Yukon Public Bodies",
        exemption_clauses=["s33", "s36", "s42"],
        parent_jurisdiction="CA",
        level="territory",
    ),
    "CA-NT": SubnationalStatutoryProfile(
        jurisdiction="CA-NT",
        regime="ATIPP",
        statute_name="Access to Information and Protection of Privacy Act (SNWT 1994 c. 20 NWT)",
        statutory_timeframe_days=30,
        timeframe_type="calendar_days",
        default_agency_scope="Northwest Territories Public Bodies",
        exemption_clauses=["s14", "s17", "s23"],
        parent_jurisdiction="CA",
        level="territory",
    ),
    "CA-NU": SubnationalStatutoryProfile(
        jurisdiction="CA-NU",
        regime="ATIPP",
        statute_name="Access to Information and Protection of Privacy Act (SNWT (Nu) 1994 c. 20 Nunavut)",
        statutory_timeframe_days=30,
        timeframe_type="calendar_days",
        default_agency_scope="Nunavut Public Bodies",
        exemption_clauses=["s14", "s17", "s23"],
        parent_jurisdiction="CA",
        level="territory",
    ),
}

# 4. German 16 Bundesländer
GERMAN_LAENDER_PROFILES: dict[str, SubnationalStatutoryProfile] = {
    "DE-BW": SubnationalStatutoryProfile(
        jurisdiction="DE-BW",
        regime="LIFG",
        statute_name="Landesinformationsfreiheitsgesetz Baden-Württemberg",
        statutory_timeframe_days=30,
        timeframe_type="calendar_days",
        default_agency_scope="Behörden des Landes Baden-Württemberg und der Kommunen",
        exemption_clauses=["§ 4", "§ 5", "§ 6"],
        parent_jurisdiction="DE",
    ),
    "DE-BY": SubnationalStatutoryProfile(
        jurisdiction="DE-BY",
        regime="BayUIG",
        statute_name="Bayerisches Umweltinformationsgesetz / Kommunale Satzungen",
        statutory_timeframe_days=30,
        timeframe_type="calendar_days",
        default_agency_scope="Bayerische Behörden (Umwelt) und Satzungsgemeinden",
        exemption_clauses=["Art 7", "Art 8"],
        parent_jurisdiction="DE",
    ),
    "DE-BE": SubnationalStatutoryProfile(
        jurisdiction="DE-BE",
        regime="BerlIFG",
        statute_name="Berliner Informationsfreiheitsgesetz",
        statutory_timeframe_days=30,
        timeframe_type="calendar_days",
        default_agency_scope="Behörden des Landes Berlin und Bezirksämter",
        exemption_clauses=["§ 6", "§ 7", "§ 8", "§ 9"],
        parent_jurisdiction="DE",
    ),
    "DE-BB": SubnationalStatutoryProfile(
        jurisdiction="DE-BB",
        regime="BbgIFG",
        statute_name="Brandenburgisches Informationsfreiheitsgesetz",
        statutory_timeframe_days=30,
        timeframe_type="calendar_days",
        default_agency_scope="Behörden des Landes Brandenburg",
        exemption_clauses=["§ 4", "§ 5", "§ 6"],
        parent_jurisdiction="DE",
    ),
    "DE-HB": SubnationalStatutoryProfile(
        jurisdiction="DE-HB",
        regime="BremIFG",
        statute_name="Bremer Informationsfreiheitsgesetz",
        statutory_timeframe_days=30,
        timeframe_type="calendar_days",
        default_agency_scope="Behörden der Freien Hansestadt Bremen",
        exemption_clauses=["§ 4", "§ 5", "§ 6"],
        parent_jurisdiction="DE",
    ),
    "DE-HH": SubnationalStatutoryProfile(
        jurisdiction="DE-HH",
        regime="HmbTG",
        statute_name="Hamburgisches Transparenzgesetz",
        statutory_timeframe_days=15,
        timeframe_type="calendar_days",
        default_agency_scope="Behörden der Freien und Hansestadt Hamburg",
        exemption_clauses=["§ 16", "§ 17", "§ 18"],
        parent_jurisdiction="DE",
    ),
    "DE-HE": SubnationalStatutoryProfile(
        jurisdiction="DE-HE",
        regime="HGIG",
        statute_name="Hessisches Gesetz über die Freiheit des Informationszugangs",
        statutory_timeframe_days=30,
        timeframe_type="calendar_days",
        default_agency_scope="Hessische Landes- und Kommunalbehörden",
        exemption_clauses=["§ 6", "§ 7", "§ 8"],
        parent_jurisdiction="DE",
    ),
    "DE-MV": SubnationalStatutoryProfile(
        jurisdiction="DE-MV",
        regime="IFG M-V",
        statute_name="Informationsfreiheitsgesetz Mecklenburg-Vorpommern",
        statutory_timeframe_days=30,
        timeframe_type="calendar_days",
        default_agency_scope="Behörden des Landes Mecklenburg-Vorpommern",
        exemption_clauses=["§ 5", "§ 6", "§ 7"],
        parent_jurisdiction="DE",
    ),
    "DE-NI": SubnationalStatutoryProfile(
        jurisdiction="DE-NI",
        regime="NTranspG",
        statute_name="Niedersächsisches Transparenzgesetz",
        statutory_timeframe_days=30,
        timeframe_type="calendar_days",
        default_agency_scope="Niedersächsische Landes- und Kommunalbehörden",
        exemption_clauses=["§ 8", "§ 9", "§ 10"],
        parent_jurisdiction="DE",
    ),
    "DE-NW": SubnationalStatutoryProfile(
        jurisdiction="DE-NW",
        regime="IFG NRW",
        statute_name="Informationsfreiheitsgesetz Nordrhein-Westfalen",
        statutory_timeframe_days=30,
        timeframe_type="calendar_days",
        default_agency_scope="Behörden des Landes Nordrhein-Westfalen und Kommunen",
        exemption_clauses=["§ 6", "§ 7", "§ 8", "§ 9"],
        parent_jurisdiction="DE",
    ),
    "DE-RP": SubnationalStatutoryProfile(
        jurisdiction="DE-RP",
        regime="LTranspG",
        statute_name="Landestransparenzgesetz Rheinland-Pfalz",
        statutory_timeframe_days=15,
        timeframe_type="calendar_days",
        default_agency_scope="Behörden des Landes Rheinland-Pfalz",
        exemption_clauses=["§ 14", "§ 15", "§ 16"],
        parent_jurisdiction="DE",
    ),
    "DE-SL": SubnationalStatutoryProfile(
        jurisdiction="DE-SL",
        regime="SIFG",
        statute_name="Saarländisches Informationsfreiheitsgesetz",
        statutory_timeframe_days=30,
        timeframe_type="calendar_days",
        default_agency_scope="Behörden des Saarlandes",
        exemption_clauses=["§ 5", "§ 6", "§ 7"],
        parent_jurisdiction="DE",
    ),
    "DE-SN": SubnationalStatutoryProfile(
        jurisdiction="DE-SN",
        regime="SächsTranspG",
        statute_name="Sächsisches Transparenzgesetz",
        statutory_timeframe_days=30,
        timeframe_type="calendar_days",
        default_agency_scope="Behörden des Freistaates Sachsen",
        exemption_clauses=["§ 13", "§ 14", "§ 15"],
        parent_jurisdiction="DE",
    ),
    "DE-ST": SubnationalStatutoryProfile(
        jurisdiction="DE-ST",
        regime="IZG LSA",
        statute_name="Informationszugangsgesetz Sachsen-Anhalt",
        statutory_timeframe_days=30,
        timeframe_type="calendar_days",
        default_agency_scope="Behörden des Landes Sachsen-Anhalt",
        exemption_clauses=["§ 4", "§ 5", "§ 6"],
        parent_jurisdiction="DE",
    ),
    "DE-SH": SubnationalStatutoryProfile(
        jurisdiction="DE-SH",
        regime="IZG-SH",
        statute_name="Informationszugangsgesetz Schleswig-Holstein",
        statutory_timeframe_days=30,
        timeframe_type="calendar_days",
        default_agency_scope="Behörden des Landes Schleswig-Holstein",
        exemption_clauses=["§ 9", "§ 10", "§ 11"],
        parent_jurisdiction="DE",
    ),
    "DE-TH": SubnationalStatutoryProfile(
        jurisdiction="DE-TH",
        regime="ThürTG",
        statute_name="Thüringer Transparenzgesetz",
        statutory_timeframe_days=30,
        timeframe_type="calendar_days",
        default_agency_scope="Behörden des Freistaats Thüringen",
        exemption_clauses=["§ 15", "§ 16", "§ 17"],
        parent_jurisdiction="DE",
    ),
}

# 5. Spanish 17 Comunidades Autónomas & 2 Ciudades Autónomas
SPANISH_AUTONOMOUS_PROFILES: dict[str, SubnationalStatutoryProfile] = {
    "ES-AN": SubnationalStatutoryProfile(
        jurisdiction="ES-AN",
        regime="LTPA",
        statute_name="Ley 1/2014 de Transparencia Pública de Andalucía",
        statutory_timeframe_days=20,
        timeframe_type="working_days",
        default_agency_scope="Junta de Andalucía y entidades locales andaluzas",
        exemption_clauses=["Art 27", "Art 28"],
        parent_jurisdiction="ES",
        level="autonomous_community",
    ),
    "ES-AR": SubnationalStatutoryProfile(
        jurisdiction="ES-AR",
        regime="LTPC",
        statute_name="Ley 8/2015 de Transparencia de la Actividad Pública de Aragón",
        statutory_timeframe_days=30,
        timeframe_type="calendar_days",
        default_agency_scope="Gobierno de Aragón y administraciones aragonesas",
        exemption_clauses=["Art 22"],
        parent_jurisdiction="ES",
        level="autonomous_community",
    ),
    "ES-AS": SubnationalStatutoryProfile(
        jurisdiction="ES-AS",
        regime="LTBG",
        statute_name="Ley 8/2018 de Transparencia del Principado de Asturias",
        statutory_timeframe_days=30,
        timeframe_type="calendar_days",
        default_agency_scope="Principado de Asturias y entidades locales",
        exemption_clauses=["Art 32"],
        parent_jurisdiction="ES",
        level="autonomous_community",
    ),
    "ES-IB": SubnationalStatutoryProfile(
        jurisdiction="ES-IB",
        regime="LTBG",
        statute_name="Llei 11/2016 de transparència i bon govern de les Illes Balears",
        statutory_timeframe_days=30,
        timeframe_type="calendar_days",
        default_agency_scope="Govern de les Illes Balears i consells insulars",
        exemption_clauses=["Art 34"],
        parent_jurisdiction="ES",
        level="autonomous_community",
    ),
    "ES-CN": SubnationalStatutoryProfile(
        jurisdiction="ES-CN",
        regime="LTAIP",
        statute_name="Ley 12/2014 de transparencia y acceso a la información de Canarias",
        statutory_timeframe_days=30,
        timeframe_type="calendar_days",
        default_agency_scope="Gobierno de Canarias y cabildos insulares",
        exemption_clauses=["Art 39"],
        parent_jurisdiction="ES",
        level="autonomous_community",
    ),
    "ES-CB": SubnationalStatutoryProfile(
        jurisdiction="ES-CB",
        regime="LTAP",
        statute_name="Ley 1/2018 de Transparencia de Cantabria",
        statutory_timeframe_days=30,
        timeframe_type="calendar_days",
        default_agency_scope="Gobierno de Cantabria y ayuntamientos",
        exemption_clauses=["Art 24"],
        parent_jurisdiction="ES",
        level="autonomous_community",
    ),
    "ES-CM": SubnationalStatutoryProfile(
        jurisdiction="ES-CM",
        regime="LTBG",
        statute_name="Ley 4/2016 de Transparencia y Buen Gobierno de Castilla-La Mancha",
        statutory_timeframe_days=30,
        timeframe_type="calendar_days",
        default_agency_scope="Junta de Comunidades de Castilla-La Mancha",
        exemption_clauses=["Art 28"],
        parent_jurisdiction="ES",
        level="autonomous_community",
    ),
    "ES-CL": SubnationalStatutoryProfile(
        jurisdiction="ES-CL",
        regime="LTPC",
        statute_name="Ley 3/2015 de Transparencia de Castilla y León",
        statutory_timeframe_days=30,
        timeframe_type="calendar_days",
        default_agency_scope="Junta de Castilla y León y entidades locales",
        exemption_clauses=["Art 21"],
        parent_jurisdiction="ES",
        level="autonomous_community",
    ),
    "ES-CT": SubnationalStatutoryProfile(
        jurisdiction="ES-CT",
        regime="Llei de transparència",
        statute_name="Llei 19/2014 de transparència i accés a la informació de Catalunya",
        statutory_timeframe_days=30,
        timeframe_type="calendar_days",
        default_agency_scope="Generalitat de Catalunya i ens locals catalans",
        exemption_clauses=["Art 21", "Art 22"],
        parent_jurisdiction="ES",
        level="autonomous_community",
    ),
    "ES-VC": SubnationalStatutoryProfile(
        jurisdiction="ES-VC",
        regime="Llei de transparència",
        statute_name="Llei 1/2022 de transparència i bon govern de la Comunitat Valenciana",
        statutory_timeframe_days=30,
        timeframe_type="calendar_days",
        default_agency_scope="Generalitat Valenciana i administracions locals",
        exemption_clauses=["Art 26"],
        parent_jurisdiction="ES",
        level="autonomous_community",
    ),
    "ES-EX": SubnationalStatutoryProfile(
        jurisdiction="ES-EX",
        regime="LGA",
        statute_name="Ley 4/2013 de Gobierno Abierto de Extremadura",
        statutory_timeframe_days=30,
        timeframe_type="calendar_days",
        default_agency_scope="Junta de Extremadura y diputaciones",
        exemption_clauses=["Art 24"],
        parent_jurisdiction="ES",
        level="autonomous_community",
    ),
    "ES-GA": SubnationalStatutoryProfile(
        jurisdiction="ES-GA",
        regime="LTBG",
        statute_name="Ley 1/2016 de transparencia y buen gobierno de Galicia",
        statutory_timeframe_days=30,
        timeframe_type="calendar_days",
        default_agency_scope="Xunta de Galicia e concellos galegos",
        exemption_clauses=["Art 25"],
        parent_jurisdiction="ES",
        level="autonomous_community",
    ),
    "ES-MD": SubnationalStatutoryProfile(
        jurisdiction="ES-MD",
        regime="LTPC",
        statute_name="Ley 10/2019 de Transparencia de la Comunidad de Madrid",
        statutory_timeframe_days=30,
        timeframe_type="calendar_days",
        default_agency_scope="Comunidad de Madrid y entidades locales madrileñas",
        exemption_clauses=["Art 37"],
        parent_jurisdiction="ES",
        level="autonomous_community",
    ),
    "ES-MC": SubnationalStatutoryProfile(
        jurisdiction="ES-MC",
        regime="LTPC",
        statute_name="Ley 12/2014 de Transparencia de la Región de Murcia",
        statutory_timeframe_days=30,
        timeframe_type="calendar_days",
        default_agency_scope="Región de Murcia y municipios",
        exemption_clauses=["Art 23"],
        parent_jurisdiction="ES",
        level="autonomous_community",
    ),
    "ES-NC": SubnationalStatutoryProfile(
        jurisdiction="ES-NC",
        regime="LFGA",
        statute_name="Ley Foral 5/2018 de Transparencia y Gobierno Abierto de Navarra",
        statutory_timeframe_days=30,
        timeframe_type="calendar_days",
        default_agency_scope="Gobierno de Navarra y entidades locales forales",
        exemption_clauses=["Art 35"],
        parent_jurisdiction="ES",
        level="autonomous_community",
    ),
    "ES-PV": SubnationalStatutoryProfile(
        jurisdiction="ES-PV",
        regime="LTPE",
        statute_name="Ley 1/2023 de Transparencia Pública de Euskadi",
        statutory_timeframe_days=20,
        timeframe_type="working_days",
        default_agency_scope="Gobierno Vasco / Eusko Jaurlaritza, diputaciones y ayuntamientos",
        exemption_clauses=["Art 38"],
        parent_jurisdiction="ES",
        level="autonomous_community",
    ),
    "ES-RI": SubnationalStatutoryProfile(
        jurisdiction="ES-RI",
        regime="LTBG",
        statute_name="Ley 3/2014 de Transparencia y Buen Gobierno de La Rioja",
        statutory_timeframe_days=30,
        timeframe_type="calendar_days",
        default_agency_scope="Gobierno de La Rioja y municipios riojanos",
        exemption_clauses=["Art 19"],
        parent_jurisdiction="ES",
        level="autonomous_community",
    ),
}

# Master Global Federation aggregating all Subnational Registries
ALL_SUBNATIONAL_PROFILES: dict[str, SubnationalStatutoryProfile] = {
    **UK_DEVOLVED_PROFILES,
    **US_SUBNATIONAL_PROFILES,
    **CANADIAN_SUBNATIONAL_PROFILES,
    **GERMAN_LAENDER_PROFILES,
    **SPANISH_AUTONOMOUS_PROFILES,
}
