$max_repeat = 5;
$interaction = "nonstopmode";
$halt_on_error = 1;
$file_line_error = 1;
$bibtex_use = 2;
$cleanup_includes_cusdep_generated = 1;

if (($ENV{"FOIO_LATEX_TARGET"} || "") eq "enhanced") {
  $pdf_mode = 4;
  $lualatex = "lualatex -interaction=nonstopmode -halt-on-error -file-line-error %O %S";
} else {
  $pdf_mode = 1;
  $pdflatex = "pdflatex -interaction=nonstopmode -halt-on-error -file-line-error %O %S";
}

$clean_ext = "aux bbl blg fdb_latexmk fls log out run.xml synctex.gz toc xdv";
